# Generated by Django 4.1.1 on 2022-11-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_coment_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
