# Generated by Django 4.1.1 on 2022-11-18 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_dislike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='_dislike', to=settings.AUTH_USER_MODEL)),
                ('_like', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(to='blog.like'),
        ),
    ]
