# Generated by Django 4.1.1 on 2022-11-21 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_alter_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='like',
            name='_like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
