# Generated by Django 4.1.1 on 2022-11-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_publishet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publishet',
            new_name='published',
        ),
    ]
